version: '3.8'
services:

  postgres:
    image: postgres
    container_name: postgresdb
    env_file: 
     - .env
    environment:
      POSTGRES_USER: backend
      POSTGRES_PASSWORD: password
      POSTGRES_DB: dbnest
    ports:
      - "5433:5432"

  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    container_name: nest-api
    env_file: 
     - .env
    ports: 
      - "3000:3000"
    depends_on: 
      - postgres
    environment:
      DATABASE_URL: ${DATABASE_URL_CONTAINER}
      CLOUDINARY_CLOUD_NAME: ${CLOUDINARY_CLOUD_NAME}
      CLOUDINARY_API_KEY: ${CLOUDINARY_API_KEY}
      CLOUDINARY_API_SECRET: ${CLOUDINARY_API_SECRET}
    command: sh -c "npx prisma migrate deploy && npm run start:prod"
