# Etapa 01: Definir a imagem base do Node.js
FROM node:20-alpine

# Etapa 02: Definir o diretório de trabalho do container
WORKDIR /app

# Etapa 03: Copiar arquivos de dependências e instalar
COPY package*.json /.
RUN npm install

# Etapa 04: Copiar o restante dos arquivos e compilar 
COPY . .
RUN npx prisma generate
RUN npm run build 

# Etapa 05: Expor a porta da aplicação
EXPOSE 3000
