#  Docker compose (significa composição)

services:

  postgres:
    image: postgres
    container_name: postgresdb
    environment: 
      POSTGRES_USER: backend
      POSTGRES_PASSWORD: password
      POSTGRES_DB: dbnest
    ports:
      - "5433:5432"
